name: Update Geolocation Database
on:
  workflow_dispatch:

jobs:
  updater:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run Script
        env:
          API_KEY_IP2LOCATION: ${{ secrets.API_KEY_IP2LOCATION }}
          OUTPUT_LOCATION: ${{ github.workspace }}/backend/include/archives/geolocation.kani.gz
        run: |
          set -e
          go run .github/workflows/geolocation.go

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add backend/include/archives/geolocation.kani.gz
          git commit -m "Geolocation Database Update" || echo "No changes to commit"
          git push